### ISSUE TITLE
Task ID: 1.1 - Read up on project brief

### ISSUE THREAD

**Issue by jc0527** [Igshanmd/ICT2101-2201-Train-Services-P2-3#2]
Task title ID: 1.1
2. To read up on project brief and have better understanding on what the project is about.
3. To identify what is required from this project.
4. Success or completion criteria. Once we all have read the project brief and understand the aim and purpose of the project
5. Allocated time - 5 days
6. Start date and end date of the issue/task 
 31st Aug- 1st Sept
7.  Owner - Jia Cheng
8.  Who is involved - Everyone in the team
Project brief has been summarised into an "infographic" on lucid chart. https://lucid.app/lucidchart/f8c8d280-a4ee-49ef-b990-62c0803eb1da/edit?viewport_loc=-238%2C-838%2C3160%2C1679%2C_LOrdLe.yyJd&invitationId=inv_f219dd47-4442-4168-8021-5f977e835c41

**Comment by Igshanmd** [comment]
Thanks all for reading up on the project brief :)

**Comment by jc0527** [comment]
Vetted

**Comment by oahyar** [comment]
Understand!

**Comment by oahyar** [comment]
Describe work done in detail: Read up and clarify doubts regarding the project brief
Work committed to branch: NIL
Does work affect deadline: NIL
Success criteria or completion: Completion upon understanding the project brief
Start date of work done: 31th Aug 2023
End date of work done: 5th Sept 2023
