### ISSUE TITLE
Task ID: 1.2.2 - Compile and share meeting minutes to the client for review

### ISSUE THREAD

**Issue by jc0527** [Igshanmd/ICT2101-2201-Train-Services-P2-3#28]
Task title ID: 1.2.2 Compiling of meeting minutes
2. Compile meeting minutes and assumptions in a word document and send over to client
3. Goal is to get the requirements approved by client
4. Success will be client concurs to the meeting minutes and assumptions
5. Allocated time : 24 hours
6. Start date: 06/09/23 1300. End date: 08/09/23 1300
7. Owner : jc0527

**Comment by oahyar** [comment]
alright, will work on it and deliver before the due date

**Comment by Igshanmd** [comment]
Feel free to ask for assistance, happy to help

**Comment by oahyar** [comment]
Email sent! waiting for reply

**Comment by KhairinNor** [comment]
Noted. Thanks for sending!

**Comment by sh4raafat** [comment]
good job guys

**Comment by oahyar** [comment]
We have received the concurrence from David. There have been some modifications requested which will be taken into consideration.
No work has been committed to branch.
The work does not affect the deadline.
Success will be if client concurs to the meeting minutes and assumptions.
Start date: 6/9/2023
End date: 8/9/2023
