### ISSUE TITLE
Task ID: 1.2 - Craft interview questions for client

### ISSUE THREAD

**Issue by oahyar** [Igshanmd/ICT2101-2201-Train-Services-P2-3#3]
Task title ID: 1.2
2. For the team to come up with questions to ask the client in order to have a better understanding of the project.
3. To analyze the project brief and come up with a set of questions to ask the clients.
4. Success or completion criteria. - Once we have come up with enough questions to clarify our doubts
5. Allocated time - 3 days
6. Start date and end date of the issue/task - By 6 Sept

**Comment by Igshanmd** [comment]
Questions is to be placed in the team's one drive

https://sitsingaporetechedu-my.sharepoint.com/:f:/g/personal/2201754_sit_singaporetech_edu_sg/Es72yiyXDwBPqYRyZfesM8oBEbnSLKCgbWNFp_9BtNJoUg?e=aamrN9

**Comment by oahyar** [comment]
Describe work done in detail: Came up with questions to check with the client
Work committed to branch: NA
Does work affect deadline: No
Success criteria or completion:  Once we have come up with enough questions to clarify our doubt
Start date of work done: 4th Sept 2023
End date of work done: 5th Sept 2023
