### ISSUE TITLE
Task ID: 1.4 - M1 report

### ISSUE THREAD

**Issue by jc0527** [Igshanmd/ICT2101-2201-Train-Services-P2-3#30]
1. Task title ID: 1.4 M1 Report submission
2. Do up M1 report 
3. Goals is to fill in the content for the M1 Report and submit before deadline
4.Success criteria: Finish up the M1 report, vet by all team members 
5. Allocated time : 1 week
6. Start date: 12/09/23 1300.
7.  End date: 22/09/23 1300
8. Owner : jc0527

**Comment by Igshanmd** [comment]
Noted, will assist :)

**Comment by ahhhfiq** [comment]
Describe work done in detail: Creating m1 report Gantt Chart
Work committed to branch: NA
Does work affect deadline: No
Success criteria or completion: Success will be team vetted through and approved
Start date of work done: 12th Sept 2023
End date of work done: TBA

**Comment by sh4raafat** [comment]
Describe work done in detail: M1 has been fully populated.
Work committed to branch: NIL
Does work affect deadline: Yes but it was completed in time.
Success criteria or completion: Team has vetted and approved the report.
Start date of work done: 17 Sept 2023
End date of work done: 20 Sept 2023

**Comment by jc0527** [comment]
yesterday
·
Collaborator


Describe work done in detail: M1 has been fully populated.
Work committed to branch: NIL
Does work affect deadline: Yes but it was completed in time.
Success criteria or completion: Team has vetted and approved the report.
Start date of work done: 17 Sept 2023
End date of work done: 20 Sept 2023

**Comment by ahhhfiq** [comment]
.
