### ISSUE TITLE
Task ID: 1.4.1- M1 Report: Introduction and Product Scope

### ISSUE THREAD

**Issue by jc0527** [Igshanmd/ICT2101-2201-Train-Services-P2-3#31]
Task title ID: 1.4.1
2. Do research on product scope and introduction and fill in the information in the report
3. Goal is to get both the product scope and introduction done
4. Success will be team vetted through and approved 
5. Allocated time : 24 hours
6. Start date: 10/09/23 1300. End date: 11/09/23 1300
7. Owner : jc0527

**Comment by oahyar** [comment]
Good work guys, let me know if you guys need anymore help 👍

**Comment by ahhhfiq** [comment]
Describe work done in detail: Crafting m1 report introduction and product scope
Work committed to branch: NA
Does work affect deadline: No
Success criteria or completion: Success will be team vetted through and approved
Start date of work done: 10th Sept 2023
End date of work done: 11th Sept 2023
