### ISSUE TITLE
Task ID: 1.4.2 - M1 Report: Intended audience/ Document review(1.3) and acknowledgements and references(1.4)

### ISSUE THREAD

**Issue by jc0527** [Igshanmd/ICT2101-2201-Train-Services-P2-3#32]
Task title ID: 1.4.2 Do up 1.3 and 1.3 of M1
2. Do up 1.3: Intended audience/ Document review and 1.4: acknowledgements and References
3. Goal is to find out the correct audience and clean up on the references 
4. Success will be team vetted through and approved
5. Allocated time : 24 hours
6. Start date: 10/09/23 1300. End date: 11/09/23 1300
7. Owner : jc0527

**Comment by Igshanmd** [comment]
Current points mentions looks good, do let me know if you need assisntance

**Comment by sh4raafat** [comment]
Describe work done in detail: 1.3 and 1.4 of M1 has been populated
Work committed to branch: NIL
Does work affect deadline: Yes but it was completed in time.
Success criteria or completion: Team has approved and vetted the content.
Start date of work done: 17 Sept 2023
End date of work done: 20 Sept 2023
