### ISSUE TITLE
Task ID: 1.4.3 - Do up 2.1: Product overview and 2.2:Product functionality of M1 report

### ISSUE THREAD

**Issue by jc0527** [Igshanmd/ICT2101-2201-Train-Services-P2-3#33]
Task title ID: 1.4.3 Do up 2.1 and 2.2 of M1 report
2. Do up 2.1: Product overview and 2.2:Product functionality
3. Goal is to describe the context and origin of product specified
4. Success will be team vetted through and approved
5. Allocated time : 1 week
6. Start date: 13/09/23 1300. End date: 20/09/23 1300
7. Owner : jc0527

**Comment by Igshanmd** [comment]
Noted, will work on it :)

**Comment by oahyar** [comment]
Working on it

**Comment by Igshanmd** [comment]
Describe work done in detail: Do up 2.1: Product overview and 2.2: Product functionality of M1 report
Work committed to branch: NIL
Does work affect deadline: NIL
Success criteria or completion: Completion upon understanding the project brief
Start date of work done: 13 Sept 2023
End date of work done: 20 Sept 2023
