### ISSUE TITLE
Task ID:1.5Gantt chart

### ISSUE THREAD

**Issue by jc0527** [Igshanmd/ICT2101-2201-Train-Services-P2-3#34]
Task title ID: 1.5 Finish the Gantt chart 
1. Use Gantt chart software or tools (e.g., Microsoft Project, Excel, or online project management software) to create the visual representation of the project timeline.
2. Goal: To provide a visual representation of a project's timeline and tasks. 
3. Success will be team vetted through and approved
4. Allocated time : 4 days
5. Start date: 13/09/23 1300. End date: 18/09/23 1300
6. Owner : jc0527

**Comment by ahhhfiq** [comment]
Describe work done in detail: Created Gannt chart using Microsoft Excel
Work committed to branch: NIL
Does work affect deadline: Yes but it was completed in time.
Success criteria or completion: Team has vetted and approved the chart.
Start date of work done: 13 Sept 2023
End date of work done: 18 Sept 2023
