### ISSUE TITLE
Task ID: 1.6 Calculate and determine Project Cost Estimation

### ISSUE THREAD

**Issue by jc0527** [Igshanmd/ICT2101-2201-Train-Services-P2-3#35]
Task title ID: 1.6 Calculate estimation of project cost
1. Calculating the estimation of a project cost involves a comprehensive analysis of various factors and resources required for the project. 
2. Goal: To provide a realistic and accurate estimate of the resources, expenses, and financial requirements needed to complete the project successfully.
3. Success will be team vetted through and approved
4. Allocated time : 4 days
5. Start date: 15/09/23 1300. End date: 18/09/23 1300
6. Owner : jc0527

**Comment by Igshanmd** [comment]
Noted, have taken note of various estimation methods top determine best methods for our case, will continue to work on it

**Comment by oahyar** [comment]
Noted on the task given. Will work it

**Comment by oahyar** [comment]
Describe work done in detail: Calculation of UCP
Work committed to branch: NIL
Does work affect deadline: NIL
Success criteria or completion: Completion upon understanding the project brief
Start date of work done: 15 Sept 2023
End date of work done: 18 Sept 2023

**Comment by jc0527** [comment]
Goodjob everyone
