### ISSUE TITLE
Task ID: 1.4.4 Do up M1 Report 2.3 Assumptions and Dependencies ​ ​3.1 User Interface Requirements

### ISSUE THREAD

**Issue by jc0527** [Igshanmd/ICT2101-2201-Train-Services-P2-3#36]
Task title ID: 1.4.4 Do up M1 Report 2.3 Assumptions and Dependencies ​ ​3.1 User Interface Requirements
1. Define how the user interacts with the system, specifying the design, layout, functionality, and usability of the user interface.
2. Goal: is to ensure that the user interface of a software application or system is designed and developed to meet the needs and expectations of its users effectively. 
3. Success will be team vetted through and approved
4. Allocated time : 6 days
5. Start date: 15/09/23 1300. End date: 19/09/23 1300
6. Owner : jc0527

**Comment by KhairinNor** [comment]
Noted. Will be working on it!

**Comment by jc0527** [comment]
Describe work done in detail: 2.3 Assumptions and Dependencies ​ ​3.1 User Interface Requirements Researched and compared with the meting minutes to confirm the assumptions and dependencies of the project

Work committed to branch: NIL
Does work affect deadline: NIL
Success criteria or completion: Completion upon understanding the project brief
Start date of work done: 15 Sept 2023
End date of work done: 19 Sept 2023
