### ISSUE TITLE
Task ID: 1.4.5 Do up M1 Report 3.2Functional Requirements​ 3.3 Use Case Model

### ISSUE THREAD

**Issue by jc0527** [Igshanmd/ICT2101-2201-Train-Services-P2-3#37]
Task title ID: 1.4.5 Do up M1 Report 3.2Functional Requirements​ 3.3 Use Case Model
1. Define detailed descriptions of the system's functionalities, features, and capabilities. They outline what the system must do to meet user needs and achieve its objectives. Use case models are a graphical representation of how users interact with a system to achieve specific goals or tasks. 
2. Goal:  is to ensure a comprehensive and well-structured approach to defining, understanding, and communicating the system's behavior and functionality.
3. Success will be team vetted through and approved
4. Allocated time : 3 days
5. Start date: 17/09/23 1300. End date: 20/09/23 1300
6. Owner : jc0527

**Comment by sh4raafat** [comment]
Describe work done in detail: 3.2 and 3.3 have been populated in M1 successfully
Work committed to branch: NIL
Does work affect deadline: Yes but it was completed in time.
Success criteria or completion: Team has approved the content.
Start date of work done: 17 Sept 2023
End date of work done: 20 Sept 2023
