### ISSUE TITLE
Task ID: 1.4.6 Do up M1 Report ​3.4 Non-functional Requirements 3.4.1 Performance Requirements 3.4.2 Safety and Security Requirements

### ISSUE THREAD

**Issue by jc0527** [Igshanmd/ICT2101-2201-Train-Services-P2-3#38]
Task title ID: 1.4.6 Do up M1 Report ​3.4
1.Performance requirements define how the system should behave in terms of speed, responsiveness, scalability, and resource utilization. 
Safety Requirements are for protecting the system, its data, and its users from potential threats and vulnerabilities. 
2. Goal: To ensure that the software or system delivers an optimal user experience/ aim to protect sensitive data from unauthorized access, disclosure, or tampering to maintain data confidentiality and integrity.
3. Success will be team vetted through and approved
4. Allocated time : 3 days
5. Start date: 19/09/23 1300. End date: 22/09/23 1300
6. Owner : jc0527

**Comment by oahyar** [comment]
Noted on the requirements

**Comment by Igshanmd** [comment]
Will work on it :)

**Comment by Igshanmd** [comment]
Describe work done in detail: Writing of  3.4 Non-functional Requirements 3.4.1 Performance Requirements 3.4.2 Safety and Security Requirements
Work committed to branch: NIL
Does work affect deadline: NIL
Success criteria or completion: Completion upon understanding the project brief
Start date of work done: 19 Sept 2023
End date of work done: 22 Sept 2023
