### ISSUE TITLE
Task ID: 1.3.1 - Create use case diagram

### ISSUE THREAD

**Issue by ahhhfiq** [Igshanmd/ICT2101-2201-Train-Services-P2-3#4]
Task title ID: 1.3.1
2. Each member is to come up with a case diagram
3. What are the goals of the task - To capture the requirements and mold them into a use case diagram.
4. Success or completion criteria - To have a use case diagram that covers all requirements.
5. Allocated time - 2 weeks
6. Start date and end date of the issue/task - 5/9/23 to 15/9/23
7. Owner - Afiq
8. What is the Priority of the task? - High

**Comment by ahhhfiq** [comment]
To update task description

**Comment by sh4raafat** [comment]
Use Case Diagrams have been finalized after recieving concurrence from client.
No work has been committed to branch.
The work does not affect the deadline.
Success will be if the use case diagram covers all requirements gathered.
Start date: 5/9/2023
End date: 15/9/2023
