### ISSUE TITLE
Task ID: 1.4.9 Do up M1 Report ​​5. Use Case Descriptions

### ISSUE THREAD

**Issue by jc0527** [Igshanmd/ICT2101-2201-Train-Services-P2-3#40]

**Comment by ahhhfiq** [comment]
Task title ID: 1.4.9
2. To come up with use case descriptions
3. What are the goals of the task - To create use case descriptions according to use case diagrams
4. Success or completion criteria - Use case descriptions that accurately describe the relevant use case diagram
5. Allocated time - 2 weeks
6. Start date and end date of the issue/task - 4/9/23 to 20/9/23
7. Owner - Afiq
8. What is the Priority of the task? - High

**Comment by sh4raafat** [comment]
Describe work done in detail: Went through all Use Case Descriptions to design them and also vetted them for consistency throughout all use cases
Work committed to branch: NIL
Does work affect deadline: Yes but it was completed in time.
Success criteria or completion: All use case diagrams accurately describe each use case diagram and are in sync with activity diagrams / wireframes
Start date of work done: 4 Sept 2023
End date of work done: 20 Sept 2023
