### ISSUE TITLE
Task ID: 1.7 Provide a graphic diagram showing the user interface for the train system and a basic description as to how users will interact

### ISSUE THREAD

**Issue by jc0527** [Igshanmd/ICT2101-2201-Train-Services-P2-3#41]
Task title ID: 1.7 
Provide a graphic diagram showing user interface and provide a basic description as to how users will interact

1. To create a design and interaction description of the user interface (UI). The goal is to create a visual representation of the application's UI and explain how users will interact with it.

2. Goal: To provide a visual representation of a project in Figma 

3.Success will be team vetted through and approved by tech lead

4.Allocated time : 2 days

5.Start date: 17/09/23 1300. End date: 20/09/23 1300

6. Owner : jc0527

**Comment by sh4raafat** [comment]
Describe work done in detail: Created a rough wireframe display of how certain pages look like such as dashboards and job assignment pages
Work committed to branch: NIL
Does work affect deadline: Yes but it was completed in time.
Success criteria or completion: Team lead has approved wireframes.
Start date of work done: 17 Sept 2023
End date of work done: 20 Sept 2023
