### ISSUE TITLE
Task ID: 1.8 To create a simple diagram for system architecture  that showcases the major components of the system

### ISSUE THREAD

**Issue by jc0527** [Igshanmd/ICT2101-2201-Train-Services-P2-3#42]
Task title ID: 1.8 
Provide the system diagram to show how the system will interact with one another and provide a basic description as to how users will interact

1. To create a design and interaction description of the system architechture. The goal is to create a visual representation of the application's architecture and explain how users will interact with it.

2. Goal: To provide a visual representation of the system architecture in Lucidchart

3. Success will be team vetted through and approved by tech lead

4. Allocated time : 2 days

5. Start date: 16/09/23 1300. End date: 22/09/23 1300

6. Owner : jc0527

**Comment by ahhhfiq** [comment]
Describe work done in detail: Created a system architecture to provide a visual representation of system interactions with Lucidchart.
Work committed to branch: NIL
Does work affect deadline: Yes but it was completed in time.
Success criteria or completion: Team has vetted and approved the diagram.
Start date of work done: 16 Sept 2023
End date of work done: 22 Sept 2023
