### ISSUE TITLE
Task ID: 2.3 Create a Component Diagram

### ISSUE THREAD

**Issue by jc0527** [Igshanmd/ICT2101-2201-Train-Services-P2-3#46]
Task title ID: 2.2 

1. Provide a graphic diagram showing the relationships between these components. For example, which components depend on others, and how do they interact?

2. Goal: To provide a visual representation of the relationships between these components

3.Success will be team vetted through and approved by tech lead

4.Allocated time : 2 weeks

5. Start date and end date of the issue/task 27/09/23 - 11/10/23

6. Owner : Sharaafat

**Comment by sh4raafat** [comment]
Describe work done in detail: Component Diagram has been vetted and completed.
Work committed to branch: NIL
Does work affect deadline: Yes but it was completed in time.
Success criteria or completion: Team has approved and vetted the content with feedback from consultation with prof.
Start date of work done: 29 Sept 2023
End date of work done: 11 Oct 2023
