### ISSUE TITLE
Task ID : 2.1 Design a Class diagram

### ISSUE THREAD

**Issue by jc0527** [Igshanmd/ICT2101-2201-Train-Services-P2-3#47]
1. visually represent the structure and relationships of classes in a system or application. It provides an overview of the classes, their attributes, methods, and the associations between them. Here's a brief description of the key elements and concepts in a class diagram:
2. What are the goals of the task?  include user interfaces, databases, backend services, and any other elements essential for the system's functionality. Consider what each component does and how they interact with each other.
3. Success or completion criteria. The system components meet the needs and expectations of its users.
4. Allocated time: 2 weeks
5. Start date and end date of the issue/task 24/09/23 - 08/10/23
6. Owner - afiq
7. What is the Priority of the task? Medium

**Comment by ahhhfiq** [comment]
Describe work done in detail: Identified the relationship of classes in the application and provide an overview of the classes.
Work committed to branch: NA
Does work affect deadline: No
Success criteria or completion: Ensure the diagram provides an overview of the classes, their attributes, methods, and the associations between them
Start date of work done: 24 September 2023
End date of work done: 8 October 2023
