### ISSUE TITLE
Task ID: 2.4 Construct a Sequence diagram

### ISSUE THREAD

**Issue by jc0527** [Igshanmd/ICT2101-2201-Train-Services-P2-3#48]
1. visually represent the interactions or sequences of messages between different objects or components in a system. It provides a time-ordered, chronological view of how various elements in a system collaborate to achieve a specific functionality or scenario
2. What are the goals of the task?  include user interfaces, databases, backend services, and any other elements essential for the system's functionality. Consider what each component does and how they interact with each other.
3. Success or completion criteria. The system components meet the needs and expectations of its users.
4. Allocated time: 2 weeks
5. Start date and end date of the issue/task 11/10/23 - 27/10/23
6. Owner - RayHao
7. What is the Priority of the task? Medium

**Comment by oahyar** [comment]
Noted! Working on it

**Comment by oahyar** [comment]
Describe work done in detail: Construct a Sequence diagram
Work committed to branch: NA
Does work affect deadline: No
Success criteria or completion:  include user interfaces, databases, backend services, and any other elements essential for the system's functionality. Consider what each component does and how they interact with each other.
Start date of work done:  11 Oct 2023
End date of work done:  27 Oct 2023
