### ISSUE TITLE
Task ID: 2.5 Verify the alignment and consistency across all 3 diagrams

### ISSUE THREAD

**Issue by jc0527** [Igshanmd/ICT2101-2201-Train-Services-P2-3#49]
1. Verify the alignment and consistency across all diagrams
2. What are the goals of the task?  include all the diagrams
3. Success or completion criteria. The system components meet the needs and expectations of its users.
4. Allocated time: 2 weeks
5. Start date and end date of the issue/task 11/10/23 - 27/10/23
6. Owner - Igshan
7. What is the Priority of the task? Medium

**Comment by Igshanmd** [comment]
Noted, working on it

**Comment by Igshanmd** [comment]
Describe work done in detail: Analyze and align all the 3 diagram to ensure they are consistent with one another. Ensure class diagram has all required classes before grouping them into components. Run through the steps in sequence diagram to ensure it is aligned as well
Work committed to branch: NIL
Does work affect deadline: Yes but it was completed in time.
Success criteria or completion: Team has vetted and approved the diagram.
Start date of work done: 11 Oct 2023
End date of work done: 27 Oct 2023
