### ISSUE TITLE
Task ID : 2.5.1 Gantt chart updating

### ISSUE THREAD

**Issue by jc0527** [Igshanmd/ICT2101-2201-Train-Services-P2-3#50]
Task title ID: 2.5.1 Update Gantt CHart
1.Update the M2 ghantt chart goals and progress along the project
2. Goal: To provide a visual representation of a project's timeline and tasks. 
3. Success will be team vetted through and approved
4. Allocated time : 5 days
5.Start date and end date of the issue/task 23/10/23 - 28/10/23
6. Owner : Khairin

**Comment by KhairinNor** [comment]
Noted. I will update accordingly.

**Comment by KhairinNor** [comment]
Describe work done in detail: Updated the timeline of the Gantt Chart according to the requirements and tasks given for M2
Work committed to branch: NIL
Does work affect deadline: Yes, some of the timeline had to change but it was all completed on time
Success criteria or completion: Team has vetted and approved the updated Gantt Chart.
Start date of work done: 23/09/23
End date of work done: 28/10/23
