### ISSUE TITLE
Task ID: 3.5 Project Prototype White Box testing

### ISSUE THREAD

**Issue by jc0527** [Igshanmd/ICT2101-2201-Train-Services-P2-3#56]
Task Title: White Box Testing Implementation
ID: 3.5

1. Description: Execute detailed white-box testing on the software to examine internal structures and workings of the application. The process involves assessing the logical flow of the code, checking internal security holes, verifying paths, and looking into the integration points within the codebase.

2. Goal: To ensure the internal operations of the code are executing as designed, to improve security, flow control, and the overall quality of the code.

3. Success Criteria: Thorough coverage of all possible execution paths within the code. Identification and rectification of logical errors and security vulnerabilities.
Code coverage metrics meet or exceed the project's predefined 
threshold. Approval of test outcomes by the development lead.

4. Allocated Time: 2 weeks

5. Start: 1/11/23, End: 7/11/23

6. Owner: Ray Hao

7. Priority: Medium

**Comment by oahyar** [comment]
working on it

**Comment by oahyar** [comment]
Describe work done in detail: White Box Testing Implementation. Implementation logical flow of code, calculating of minimum number of paths and verifying the path
Work committed to branch: NA
Does work affect deadline: No
Success criteria or completion: Thorough coverage of all possible execution paths within the code. Identification and rectification of logical errors and security vulnerabilities. Code coverage metrics meet or exceed the project's predefined threshold. Approval of test outcomes by the development lead.
Start date of work done: 1st Nov 2023
End date of work done: 10th Nov 2023
