### ISSUE TITLE
Task ID: 3.6 Project Management

### ISSUE THREAD

**Issue by jc0527** [Igshanmd/ICT2101-2201-Train-Services-P2-3#57]
Task title ID: 3.6 Update Gantt Chart
1. Update the M3 Ghantt chart goals and progress along the project

2. Goal: To provide a visual representation of a project's timeline and tasks.
 
3. Success will be team vetted through and approved

4. Allocated time: 5 days

5. Start date and end date of the issue 1/11/23 - 10/11/23

6. Owner: Khairin
 
7. Priority : Medium

**Comment by KhairinNor** [comment]
Describe work done in detail: Updated the timeline of the Gantt Chart according to the requirements and tasks given for M3
Work committed to branch: NIL
Does work affect deadline: No.
Success criteria or completion: Team has vetted and approved the updated Gantt Chart.
Start date of work done: 1/11/23
End date of work done: 10/11/23
