### ISSUE TITLE
Task ID: 1.2.1 - Conduct client interview for requirement gathering

### ISSUE THREAD

**Issue by Igshanmd** [Igshanmd/ICT2101-2201-Train-Services-P2-3#6]
Task title ID: 1.2.1
2. To interview clients to iron out project requirements and clarify any doubts
3. To be more clear on what the project is and what are the features and requirements needed (requirements gathering)
4. Success or completion criteria.  -
5. Allocated time - 15 Minutes
6. Start date and end date - 5 Sep, 1 PM
7. Owner - Igshan
8. What is the Priority of the task? - HIGH

**Comment by oahyar** [comment]
Describe work done in detail: Interviewing the client, gathering the requirements, and clear doubts
Work committed to branch: NA
Does work affect deadline: No
Success criteria or completion: NA
Start date of work done: 5th Sept 2023
End date of work done: 8th Sept 2023
